### ISSUE TITLE
countdown timer 不斷出現

### ISSUE THREAD

**Issue by miterfrants** [hahow/plyr#41]
```function _cancelRequests() {
.....
plyr.media.setAttribute('src', 'https://cdn.selz.com/plyr/blank.mp4');
```
上面這一段在某一些瀏覽器會 trigger ended event
造成倒數計時提會不斷的出現

**Comment by miterfrants** [comment]
正在詢問 @amowu 
_setQuality 為什麼要使用 _updateSources function 來替換影片來源

**Comment by amowu** [comment]
因為 `setQuality` 是把 source 移到第一個，然後要觸發 `updateSource` 才可以重新讀取第一個 source
